

# PATHS

face_detection_model : "./serialized/face_detection_model/res10_300x300_ssd_iter_140000.caffemodel"
face_detection_protopath : "./serialized/face_detection_model/deploy.prototxt"
dataset : "./dataset"
training_set : "/datascience/datasets/faces/UTKFace_train"
validation_set : "/datascience/datasets/faces/UTKFace_val"
face_embedding_model : "./serialized/face_embedding_model/openface.nn4.small2.v1.t7"
images : "./images"


# RESOLUTION

face_resolution : !!python/tuple [200, 200]
video_resolution : !!python/tuple [500, 600]


# Face detector's confidence

confidence : 0.6


# Number of photos per person to take

nb_photos : 20
